// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'applicant.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_Applicant _$ApplicantFromJson(Map<String, dynamic> json) => _Applicant(
  id: (json['id'] as num?)?.toInt(),
  appId: json['app_id'] as String?,
  fname: json['fname'] as String?,
  mname: json['mname'] as String?,
  lname: json['lname'] as String?,
  suffix: json['suffix'] as String?,
  dob: json['dob'] as String?,
  caddress: json['caddress'] as String?,
  paddress: json['paddress'] as String?,
  age: (json['age'] as num?)?.toInt(),
  marital: json['marital'] as String?,
  gender: json['gender'] as String?,
  religion: json['religion'] as String?,
  nationality: json['nationality'] as String?,
  email: json['email'] as String?,
  phone: json['phone'] as String?,
  mmname: json['mmname'] as String?,
  ffname: json['ffname'] as String?,
  educ: json['educ'] as String?,
  courset: json['courset'] as String?,
  sss: json['sss'] as String?,
  tin: json['tin'] as String?,
  philh: json['philh'] as String?,
  pagibig: json['pagibig'] as String?,
  ename: json['ename'] as String?,
  eaddress: json['eaddress'] as String?,
  relationship: json['relationship'] as String?,
  ephone: json['ephone'] as String?,
  status: json['status'] as String?,
  agreed: json['agreed'] as String?,
  callStatus: json['call_status'] as String?,
  site: json['site'] as String?,
  submitted: json['submitted'] as String?,
);

Map<String, dynamic> _$ApplicantToJson(_Applicant instance) =>
    <String, dynamic>{
      'id': instance.id,
      'app_id': instance.appId,
      'fname': instance.fname,
      'mname': instance.mname,
      'lname': instance.lname,
      'suffix': instance.suffix,
      'dob': instance.dob,
      'caddress': instance.caddress,
      'paddress': instance.paddress,
      'age': instance.age,
      'marital': instance.marital,
      'gender': instance.gender,
      'religion': instance.religion,
      'nationality': instance.nationality,
      'email': instance.email,
      'phone': instance.phone,
      'mmname': instance.mmname,
      'ffname': instance.ffname,
      'educ': instance.educ,
      'courset': instance.courset,
      'sss': instance.sss,
      'tin': instance.tin,
      'philh': instance.philh,
      'pagibig': instance.pagibig,
      'ename': instance.ename,
      'eaddress': instance.eaddress,
      'relationship': instance.relationship,
      'ephone': instance.ephone,
      'status': instance.status,
      'agreed': instance.agreed,
      'call_status': instance.callStatus,
      'site': instance.site,
      'submitted': instance.submitted,
    };
